# Automatically fetch and merge latest tag to mamolinux/stable for new stable releases
name: Update mamolinux/stable branch

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for new tags
  push:
    tags:
      - "*.*.*"
  workflow_dispatch: # on button click
    inputs:
      action:
        description: 'Select the action to run'
        required: true
        type: choice
        options:
          - Update Stable Branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job handles the Stable Branch Update, whether from a schedule or manual trigger
  stable_update_job:
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags')) ||
      (github.event_name == 'workflow_dispatch')
    uses: mamolinux/github-actions/.github/workflows/update-stable-branch.yml@main
    with:
      target_branch: 'mamolinux/stable'
